apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: go-rqzktkje
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/go-rqzktkje:0d39a83247c7f5d8864470258afaa6e40e46a6fe@sha256:ee91e2b8c356ccdb4e6e80f02f1053ec377aee50f03fb0da63ad91291f20f089
          name: container-image
